Retain previously added breadcrumbs whenever a new breadcrumb is added
bugsnag/bugsnag-android-ndk pull request #12
Opened 2018-03-19 15:51 UTC by fractalwrench

This changeset avoids clearing all breadcrumbs everytime a new breadcrumb is added, by omitting a call to `bugsnag_event_clear_breadcrumbs`. Previously this method freed memory, then allocated new memory for each breadcrumb.

Reducing this churn by retaining previously added values will partially address #10, which is caused by multiple threads attempting to free/allocate memory at the same time. I've found that running the [reproduction case](https://github.com/bugsnag/bugsnag-android-ndk/tree/segfault-repro-case) results in less frequent signals when this fix is applied.

One concern with this change is that we should be careful it hasn't introduced any memory leaks. I believe the `bugsnag_event_add_breadcrumb` method was freeing the required memory in the first place so `bugsnag_event_clear_breadcrumbs` wasn't necessary, but it would be good to confirm this.

2018-03-19 16:30 UTC, Pezzah commented
I think we might need two different methods here, one for just adding a new breadcrumb (where we assume that the others are already in sync) and one for cloning / copying all existing breadcrumbs. 

This method is not always called when adding a new breadcrumb, it is also called when initializing the NDK notifier, and also to clear all breadcrumbs (see https://github.com/bugsnag/bugsnag-android/blob/master/sdk/src/main/java/com/bugsnag/android/Client.java#L1221).

2018-03-20 17:12 UTC, kattrali requested changes
Ditto @Pezzah's comment, adding resolution of in-person conversation. The way forward is to:

* Clear and iterate over breadcrumbs when doing the initial population and when `clearBreadcrumbs()` is called from the Java side 
* Separate adding a breadcrumb into a different event which only appends to the collection

2018-03-21 08:39 UTC, Pezzah commented
When adding a breadcrumb will it be thread safe to assume that it is the last breadcrumb in the list that needs to be added? or does the addBreadcrumb method need to pass through parameters for the name / type?

2018-04-04 17:17 UTC, maltzj commented
_gentle poke from a concerned citizen_

2018-04-18 17:45 UTC, maltzj commented
_gentle nudge_

2018-04-19 16:19 UTC, fractalwrench commented
Hi @maltzj - sorry for missing this. This ticket is currently still in progress, as it has a bit wider an impact than initially thought.

2018-04-25 13:33 UTC, maltzj commented
Thanks for the update @fractalwrench.  Let me know if there's any other insight I can provide here.

2018-09-12 14:31 UTC, closed without merging

2018-09-12 15:19 UTC, fractalwrench commented
Closing as this will be addressed by https://github.com/bugsnag/bugsnag-android/pull/369